server:
  port: 8080
  mode: debug

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: gva
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0 